substitutions:
  device_name: zahrada
  friendly_name: "Zahrada"
packages:
  - !include templates/sonoff-mini-r4-switch-with-button.yaml

<<: !include components/ota.yaml
<<: !include components/wifi.yaml