substitutions:
  name: zasuvka-mycka
  friendly_name: "MyÄka"
packages:
  athom.smart-plug: !include templates/athom-smart-plug-template-v2.yaml
esphome:
  name_add_mac_suffix: false

<<: !include components/ota.yaml
<<: !include components/wifi.yaml